language: node_js
node_js: 12
services: docker
env:
  - DOCKER_COMPOSE_VERSION=1.24.1
branches: 
  only: 
    - master
install:
  - docker-compose -f udagram-deployment/docker/docker-compose-build.yaml build --parallel
script:
  echo "done"
